version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.5

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
    deploy:
      working_directory: ~/repo
      docker:
        - image: circleci/node:10.5
      steps:
        - checkout
        - run: - yarn netlify -d public --site-id ${DEV_SITE_ID} --access-token ${NETLIFY_TOKEN}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release